name: pay
description: A new flutter plugin project.
version: 0.0.3
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  #应用内购买(ios和google play)
  in_app_purchase: ^0.3.4+16

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  plugin:
    platforms:
      android:
        package: com.pinto.pay
        pluginClass: PayPlugin
      ios:
        pluginClass: PayPlugin


